### ISSUE TITLE
[BUG] CDK installs incorrect (latest build) discovery-ec2 plugin 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-cluster-cdk#35]
### What is the bug?

In https://github.com/opensearch-project/opensearch-cluster-cdk/blob/fce305519cd84197fcbe2daa60880319aba330ec/lib/infra/infra-stack.ts#L450 the code installs discovery-ec2 from `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/${props.opensearchVersion}/latest/linux/${props.cpuArch}`. This is almost always a different build than the one in `distributionUrl`, which ~can~ will cause runtime incompatibilities.

### What is the expected behavior?

Extract and install the plugin from the .tar.gz specified in `distributionUrl`.

**Comment by prudhvigodithi** [comment]
[Untriage]
@rishabh6788 can you please take a look at this and add your thoughts.
Thanks

**Comment by rishabh6788** [comment]
This issue came up when we wanted to test an old build of OpenSearch and it installed the latest version of ec2 plugin which was upgraded to use AWS SDK v2. 
Since we allow users to specify custom artifact urls it becomes very difficult to find corresponding version of ec2 plugin, thus, falling back on latest staged version of native plugin becomes more reliable. 

We haven't come across this issue again as there hasn't been any major breaking change introduced in native plugins. 
Closing this issue for now.
