### ISSUE TITLE
[BUG] Suffix parameter not getting used while creating the network stack

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/opensearch-cluster-cdk#50]
### What is the bug?
Suffix parameter not getting used while creating the network stack, but for infra stack the suffix is getting picked up.

### How can one reproduce the bug?
Deploy multiple clusters in same account with different suffix and see that network stack is same for both the clusters.

### What is the expected behavior?
If suffix is passed then network stack should also be created with the suffix.

### What is your host/environment?
NA

### Do you have any screenshots?
NA

### Do you have any additional context?
NA

**Comment by navneet1v** [comment]
![Screen Shot 2023-08-30 at 11 40 21 PM](https://github.com/opensearch-project/opensearch-cluster-cdk/assets/6162415/671a9741-60e2-4de7-ac7e-27503786fc1f)

**Comment by rishabh6788** [comment]
@navneet1v thanks for creating the issue. This is by design due to following:
1. Limit on number of VPCs that are allowed per region and per account.
2. If the user is not careful and doesn't update the VPC CIDRs and subnets while trying to create new VPCs on every new deployment, this will result in CIDR collision and stack deployment failure. 
3. Since this is used for our nightly run automation as well, it will become difficult to scale and manage so many VPCs during runs or debugging failures. 

In case you want to use multiple VPCs you can create manually in your account and then use `-c vpcId` context parameter to pass them.
